name: Build and Publish image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'app/dockerfile'
      - 'app/main.py'

jobs:
  publish_images: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_image
        run: docker build ./app/ -t mimurphy94/python-flask-api-project-main:python-project
      - name: push image to docker hub
        run: |
          docker login -u mimurphy94 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mimurphy94/python-flask-api-project-main:python-project
        
